"""add master_data_requests and audit_log tables, master_records deleted_at

Revision ID: ea31ae1c8001
Revises: 0a28bb5792e7
Create Date: 2026-08-12 22:46:13.394363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea31ae1c8001'
down_revision: Union[str, None] = '0a28bb5792e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: autogenerate also proposed dropping+recreating
    # ix_master_records_name_trgm and ix_master_records_name_tsv (same false
    # positive as migration 4c2009b56c83 — both indexes were created via raw
    # SQL and aren't visible to SQLAlchemy metadata comparison). Removed from
    # this migration; left untouched in the database.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_data_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('target_record_id', sa.Integer(), nullable=True),
    sa.Column('proposed_attributes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_data_requests_domain'), 'master_data_requests', ['domain'], unique=False)
    op.create_index(op.f('ix_master_data_requests_status'), 'master_data_requests', ['status'], unique=False)
    op.add_column('master_records', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_records', 'deleted_at')
    op.drop_index(op.f('ix_master_data_requests_status'), table_name='master_data_requests')
    op.drop_index(op.f('ix_master_data_requests_domain'), table_name='master_data_requests')
    op.drop_table('master_data_requests')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
